#Codoffee-Quiz-Maker:--------------------------------------------------------------------------------------------------------------------------------------------------
#import-packages:------------------------------------------------------------------------------------------------------------------------------------------------------
import playsound
import time
import os
import turtle as t
import tkinter as tk
import ftplib
import pyautogui
from datetime import date
from turtle import mainloop, Turtle
from datetime import datetime
from threading import Thread
from tkinter import filedialog
from tkinter import *
import tkinter
import jdatetime
import requests
from tkinter import messagebox
#start-progress:-------------------------------------------------------------------------------------------------------------------------------------------------------
m=t.Turtle()
m.ht()
dcw=t.Turtle()
dcw.ht()
try:
    #GUI1 making:
    t.setup(410,410)
    t.title('Codoffee Library Manager 1.3 | مدير کتابخانه "کاتب" 1.3')
    t.speed(0)
    t.ht()
    scr=t.Screen()
    file=open("db1.db")
    bg_color=file.read()
    file.close()
    file=open("db2.db")
    p_color=file.read()
    file.close()
    file=open("db4.db")
    t_v=file.read()
    file.close()
    t.bgcolor("lightgreen")
    t.pencolor("gray")
    t.write("C",align="center",font=("impact",50))
    time.sleep(0.2)
    t.undo()
    t.pencolor("brown")
    t.write("CO",align="center",font=("impact",50))
    time.sleep(0.2)
    t.undo()
    t.pencolor("gray")
    t.write("COD",align="center",font=("impact",50))
    time.sleep(0.2)
    t.undo()
    t.pencolor("brown")
    t.write("CODO",align="center",font=("impact",50))
    time.sleep(0.2)
    t.undo()
    t.pencolor("gray")
    t.write("CODOFF",align="center",font=("impact",50))
    time.sleep(0.2)
    t.undo()
    t.pencolor("brown")
    t.write("CODOFFEE",align="center",font=("impact",50))
    time.sleep(0.2)
    t.pu()
    t.goto(0,-35)
    t.pd()
    t.pencolor("darkblue")
    t.write("Library Manager",align="center",font=("Comic Sans MS",25,("bold")))
    t.pu()
    t.goto(0,-161)
    t.pd()
    t.pencolor("black")
    t.write("Designed as requested by #helli5_school",align="center",font=("Arial",7,("bold")))
    t.pu()
    t.goto(0,-178)
    t.pd()
    t.pencolor("black")
    t.write("© 2018 Codoffee | All rights reserved.",align="center",font=("Arial",7,("bold")))
    t.pu()
    t.goto(0,-195)
    t.pd()
    t.pencolor("black")
    t.write(".تمامي حقوق اين نرم افزار محفوظ است",align="center",font=("B Tite",10))
    playsound.playsound("Codoffee Audio.mp3")
    t.pensize(1)
    file=open("db4.db")
    t_j_o=file.read()
    file.close()
    if(t_j_o=="0"):
        t.clear()
        t.title("Sign-in | ورود")
        t.pu()
        t.goto(0,-10)
        t.pd()
        t.bgcolor("lightyellow")
        t.pencolor("purple")
        t.write("Sign-in",align="center",font=("Impact",35))
        t.pu()
        t.goto(-2,-60)
        t.pd()
        t.pencolor("darkblue")
        t.write("ورود",align="center",font=("B Titr",25))
        numw=t.Turtle()
        numw.pu()
        numw.goto(-30,-138)
        numw.pd()
        numw.ht()
        numw.write("1",align="center",font=("Impact",11))
        your_name=t.textinput("Sign-in | ورود","Username of Management | *Enter in english only*:    \n:*نام کاربري مديريت، *الزاما انگليسي وارد کنيد    ")
        numw.forward(10)
        numw.write("2",align="center",font=("Impact",11))
        admin_id=t.textinput("Sign-in | ورود","Codoffee ID | *Enter in english only*:  \n:*کدفي آيدي، *الزاما انگليسي وارد کنيد    ")
        numw.forward(10)
        numw.write("3",align="center",font=("Impact",11))
        admin_pass=pyautogui.password('.کنيد وارد انگليسي الزاما ،آيدي کدفي عبور رمز')
        numw.clear()
        try:
            ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
        except:
            playsound.playsound("12.mp3")
            exit()
        try:
            ftp.cwd("htdocs/"+admin_id+'/'+admin_pass)
            try:
                ftp.cwd("LB")
            except:
                ftp.mkd('LB')
        except:
            playsound.playsound("17.mp3")
            exit()
        file=open("db6.db",'w')
        file.write(admin_id)
        file.close()
        file=open("db7.db",'w')
        file.write(admin_pass)
        file.close()
        file=open("db5.db","w")
        file.write(your_name)
        file.close()
    file=open("db6.db",'r')
    admin_id=file.read()
    file.close()
    file=open("db7.db",'r')
    admin_pass=file.read()
    file.close()
    try:
        try:
            m.clear()
            t.setup(620,510)
            t.title('مدير کتابخانه "کاتب" 1.3 | حساب مدير')
            m=t.Turtle()
            m.ht()
            m.speed(0)
            t.clear()
            t.bgcolor(bg_color)
            t.pencolor("darkred")
            t.fillcolor("#a3a375")
            t.pensize(1)
            t.pu()
            t.goto(-310,210)
            t.pd()
            t.goto(310,210)
            t.pu()
            t.goto(-310,215)
            t.pd()
            t.goto(310,215)
            t.pu()
            t.goto(-310,220)
            t.pd()
            t.goto(310,220)
            t.pd()
            t.begin_fill()
            t.goto(310,220)
            t.goto(310,255)
            t.goto(-310,255)
            t.goto(-310,220)
            t.end_fill()
            t.pu()
            t.goto(-310,-190)
            t.pd()
            t.goto(310,-190)
            t.pu()
            t.goto(-310,-195)
            t.pd()
            t.goto(310,-195)
            t.pu()
            t.goto(-310,-200)
            t.pd()
            t.goto(310,-200)
            t.pu()
            t.goto(-310,-205)
            t.pd()
            t.goto(310,-205)
            t.pu()
            t.goto(-310,-210)
            t.pd()
            t.begin_fill()
            t.goto(310,-210)
            t.goto(310,-255)
            t.goto(-310,-255)
            t.goto(-310,-210)
            t.end_fill()
            button1=Turtle()
            image="transfer.gif"
            scr.addshape(image)
            button1.shape(image)
            button1.speed(0)
            button1.pu()
            button1.goto(-3,-195)
            button1.pd()
            t.pencolor("black")
            t.pu()
            t.goto(-3,-240)
            t.write("انتقالات",align="center",font=("B Kourosh",16))
            button2=Turtle("square")
            button2.speed(4)
            button2.pu()
            button2.goto(0,225)
            button2.pd()
            button2.shapesize(1.2)
            button2.fillcolor("green")
            time.sleep(0.5)
            button2.fillcolor("blue")
            time.sleep(0.5)
            try:
                button2.fillcolor("dark"+p_color)
            except:
                try:
                    button2.fillcolor("light"+p_color)
                except:
                    button2.fillcolor(p_color)
            button2.left(360)
            t.pu()
            t.goto(1,191)
            t.pd()
            t.pencolor(p_color)
            t.write("شخصي سازي",align="center",font=("B Kourosh",13))
            button3=Turtle()
            image="user.gif"
            scr.addshape(image)
            button3.shape(image)
            button3.speed(0)
            button3.pu()
            button3.goto(116,-195)
            button3.pd()
            t.pu()
            t.goto(116,-233)
            t.pd()
            t.pencolor("black")
            t.write("کاربر ها",align="center",font=("B Kourosh",13))
            button4=Turtle()
            image="book.gif"
            scr.addshape(image)
            button4.shape(image)
            button4.speed(0)
            button4.pu()
            button4.goto(-120,-195)
            button4.pd()
            t.pu()
            t.goto(-118,-233)
            t.pd()
            t.pencolor("black")
            t.write("کتاب ها",align="center",font=("B Kourosh",13))
            button5=Turtle()
            image="info.gif"
            scr.addshape(image)
            button5.shape(image)
            button5.speed(0)
            button5.pu()
            button5.goto(100,225)
            button5.pd()
            button5.left(90)
            t.pu()
            t.goto(100,185)
            t.pd()
            t.pencolor("black")
            t.write("اطلاعات",align="center",font=("B Kourosh",13))
            button6=Turtle()
            image="message.gif"
            scr.addshape(image)
            button6.shape(image)
            button6.speed(0)
            button6.pu()
            button6.goto(-100,225)
            button6.pd()
            button6.right(90)
            t.pu()
            t.goto(-100,185)
            t.pd()
            t.pencolor("black")
            t.write("اعلانات",align="center",font=("B Kourosh",13))
            if(t_v=="0"):
                m.pu()
                m.goto(0,60)
                m.pd()
                m.pencolor("brown")
                m.write("،خوش آمديد",align="center",font=("B Nazanin",15,("bold")))
                m.pu()
                m.goto(0,30)
                m.pd()
                m.pencolor("black")
                m.write('"به مدير کتابخانه "کاتب',align="center",font=("B Nazanin",13,("bold")))
                file=open("db4.db","w")
                file.write("1")
                file.close()
                time.sleep(3)
            def buton1(x,y):
                try:
                    m.clear()
                    m.pencolor("darkblue")
                    m.pu()
                    m.goto(0,20)
                    m.pd()
                    m.write('.لطفا نوع درخواست را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                    what=t.textinput("انتقالات",": ( دريافت / تحويل )")
                    if(what=="دريافت"):
                        m.pencolor("darkblue")
                        m.clear()
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write(".لطفا شابک کتاب را وارد کنيد",align="center",font=("B Nazanin",13,("bold")))
                        shabak_get=t.textinput("دريافت",": شابک کتاب")
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        try:
                            ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books/"+shabak_get)
                            try:
                                ftp.cwd("exists")
                                m.pencolor("darkblue")
                                m.clear()
                                m.pu()
                                m.goto(0,20)
                                m.pd()
                                m.write('.لطفا کد ملي کاربر را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                                melli_code_get=t.textinput("دريافت",": کد ملي کاربر")
                                m.pencolor("darkblue")
                                m.clear()
                                m.pu()
                                m.goto(0,20)
                                m.pd()
                                m.write('.لطفا رمز عبور کاربر را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                                pass_code_get=pyautogui.password('.کنيد وارد انگليسي الزاما ،کاربر عبور رمز')
                                ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                                try:
                                    ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users/"+melli_code_get+'/'+pass_code_get+"/books")
                                    num=ftp.nlst()
                                    if(len(num)<4):
                                        now=datetime.now()
                                        ndate=jdatetime.datetime.now().strftime("%Y-%m-%d")
                                        ftp.mkd(shabak_get)
                                        ftp.cwd(shabak_get)
                                        ftp.mkd(ndate)
                                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                                        ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books/"+shabak_get)
                                        ftp.rmd("exists")
                                        m.pencolor("brown")
                                        m.clear()
                                        m.pu()
                                        m.goto(0,20)
                                        m.pd()
                                        m.write(".کتاب با موفقيت توسط کاربر دريافت شد",align="center",font=("B Nazanin",13,("bold")))
                                    else:
                                        m.pencolor("purple")
                                        m.clear()
                                        m.pu()
                                        m.goto(0,20)
                                        m.pd()
                                        m.write('.کاربر حد مجاز دريافت کتاب را رد کرده است',align="center",font=("B Nazanin",13,("bold")))      
                                except:
                                    m.pencolor("purple")
                                    m.clear()
                                    m.pu()
                                    m.goto(0,20)
                                    m.pd()
                                    m.write('.کد ملي کاربر يا رمز عبور اشتباه وارد شده',align="center",font=("B Nazanin",13,("bold")))
                            except:
                                m.pencolor("purple")
                                m.clear()
                                m.pu()
                                m.goto(0,20)
                                m.pd()
                                m.write('.کتاب در استفاده ي کاربر ديگري قرار دارد',align="center",font=("B Nazanin",13,("bold")))
                        except:
                            m.pencolor("purple")
                            m.clear()
                            m.pu()
                            m.goto(0,20)
                            m.pd()
                            m.write('.کتابي با اين شابک ثبت نشده است',align="center",font=("B Nazanin",13,("bold")))
                            time.sleep(1.5)
                            m.pencolor("darkblue")
                            m.clear()
                            m.pu()
                            m.goto(0,20)
                            m.pd()
                            m.write('...در حال ثبت کتاب',align="center",font=("B Nazanin",13,("bold")))
                            name_book=t.textinput("افزودن",":*نام کتاب، *الزاما انگليسي وارد کنيد")
                            ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                            ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books")
                            ftp.mkd(shabak_get)
                            ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                            ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books/"+shabak_get)
                            ftp.mkd(name_book)
                            ftp.mkd("exists")
                            m.clear()
                            m.pencolor("brown")
                            m.pu()
                            m.goto(0,20)
                            m.pd()
                            m.write('.ثبت کتاب با موفقيت انجام شد',align="center",font=("B Nazanin",13,("bold")))
                    elif(what=="تحويل"):
                        m.pencolor("darkblue")
                        m.clear()
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write(".لطفا شابک کتاب را وارد کنيد",align="center",font=("B Nazanin",13,("bold")))
                        shabak_get=t.textinput("تحويل",": شابک کتاب")
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        try:
                            ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books/"+shabak_get)
                            try:
                                ftp.cwd("exists")
                                m.pencolor("purple")
                                m.clear()
                                m.pu()
                                m.goto(0,20)
                                m.pd()
                                m.write('.کتاب در استفاده ي کاربري قرار ندارد',align="center",font=("B Nazanin",13,("bold")))
                            except:
                                m.pencolor("darkblue")
                                m.clear()
                                m.pu()
                                m.goto(0,20)
                                m.pd()
                                m.write('.لطفا کد ملي کاربر را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                                melli_code_get=t.textinput("تحويل",": کد ملي کاربر")
                                m.pencolor("darkblue")
                                m.clear()
                                m.pu()
                                m.goto(0,20)
                                m.pd()
                                m.write('.لطفا رمز عبور کاربر را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                                pass_code_get=pyautogui.password('.کنيد وارد انگليسي الزاما ،کاربر عبور رمز')
                                ftp.quit()
                                ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                                try:
                                    ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                                    ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users/"+melli_code_get+"/"+pass_code_get+"/books"+"/"+shabak_get)
                                    x=ftp.nlst()
                                    ftp.rmd(x[2])
                                    ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                                    ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users/"+melli_code_get+"/"+pass_code_get+"/books")
                                    ftp.rmd(shabak_get)
                                    ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                                    ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books/"+shabak_get)
                                    ftp.mkd("exists")
                                    m.pencolor("brown")
                                    m.clear()
                                    m.pu()
                                    m.goto(0,20)
                                    m.pd()
                                    m.write(".کتاب با موفقيت به کتابخانه تحويل داده شد",align="center",font=("B Nazanin",13,("bold")))
                                except:
                                    m.pencolor("purple")
                                    m.clear()
                                    m.pu()
                                    m.goto(0,20)
                                    m.pd()
                                    m.write('.کد ملي کاربر يا رمز عبور اشتباه وارد شده',align="center",font=("B Nazanin",13,("bold")))
                        except:
                            m.pencolor("purple")
                            m.clear()
                            m.pu()
                            m.goto(0,20)
                            m.pd()
                            m.write('.کتابي با اين شابک ثبت نشده است',align="center",font=("B Nazanin",13,("bold")))
                except:
                    m.pencolor("purple")
                    m.clear()
                    m.pu()
                    m.goto(0,20)
                    m.pd()
                    m.write('.مشکلي در بخش انتقالات رخ داده است',align="center",font=("B Nazanin",13,("bold")))
            def buton2(x,y):
                os.startfile("color.pdf")
                m.clear()
                m.pu()
                m.goto(0,0)
                m.pd()
                m.pencolor("darkblue")
                m.write("شخصي سازي",align="center",font=("B Titr",35))
                time.sleep(4)
                m.clear()
                m.pu()
                m.goto(0,20)
                m.pd()
                m.pencolor("darkblue")
                m.write(".لطفا رنگ پس زمينه را وارد کنيد",align="center",font=("B Nazanin",15,("bold")))
                bg_color_u=t.textinput("شخصي سازي","                :رنگ پس زمينه، الزاما انگليسي").lower()
                m.clear()
                m.write(".لطفا رنگ مداد را انتخاب کنيد",align="center",font=("B Nazanin",15,("bold")))
                p_color_u=t.textinput("شخصي سازي","                   :رنگ مداد، الزاما انگليسي").lower()
                colors=["blue","green","yellow","red","black","white","gray","orange","pink","purple"]
                if(bg_color_u in colors)and(p_color_u in colors)and(b_color_u in colors):
                    file=open("db1.db","w")
                    file.write(bg_color_u)
                    file.close()
                    file=open("db2.db","w")
                    file.write(p_color_u)
                    file.close()
                else:
                    m.clear()
                    m.pu()
                    m.goto(0,20)
                    m.pd()
                    m.pencolor("purple")
                    m.write(".متاسفيم، رنگ هاي وارد شده مشخص شده نيستند",align="center",font=("B Nazanin",15,("bold")))
            def buton3(x,y):
                try:
                    m.clear()
                    m.pencolor("darkblue")
                    m.pu()
                    m.goto(0,20)
                    m.pd()
                    m.write('.لطفا نوع درخواست را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                    what=t.textinput("کاربر ها",": ( افزودن / حذف / ليست )")
                    if("افزودن"in what):
                        m.clear()
                        m.pencolor("darkblue")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.لطفا کد ملي فرد را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                        meli_code_get=t.textinput("افزودن",": کد ملي فرد")
                        m.clear()
                        m.pencolor("darkblue")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.لطفا رمز عبور فرد را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                        password_get=pyautogui.password('.کنيد وارد انگليسي الزاما ،کاربر عبور رمز')
                        m.clear()
                        m.pencolor("darkblue")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.لطفا نام و نام خانوادگي فرد را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                        name_get=t.textinput("افزودن",":*نام و نام خانوادگي فرد، *الزاما انگليسي وارد کنيد")
                        m.clear()
                        m.pencolor("darkblue")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.لطفا شماره تلفن فرد را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                        number_get=t.textinput("افزودن",": شماره تلفن فرد")
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users")
                        ftp.mkd(meli_code_get)
                        ftp.cwd(meli_code_get)
                        ftp.mkd(password_get)
                        ftp.cwd(password_get)
                        ftp.mkd(name_get)
                        ftp.mkd(number_get)
                        ftp.mkd("books")
                        m.clear()
                        m.pencolor("brown")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.ثبت کاربر جديد با موفقيت انجام شد',align="center",font=("B Nazanin",13,("bold")))
                    elif("حذف"in what):
                        m.clear()
                        m.pencolor("darkblue")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.لطفا کد ملي کاربر را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                        meli_code_get=t.textinput("افزودن",": کد ملي فرد")
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users/"+meli_code_get)
                        pass_of_u=ftp.nlst()
                        ftp.cwd(pass_of_u[2])
                        jojok=ftp.nlst()
                        for i in range(0,len(jojok)):
                            try:
                                ftp.rmd(jojok[i])
                            except:
                                pass
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users/"+meli_code_get)
                        pass_of_u=ftp.nlst()
                        ftp.rmd(pass_of_u[2])
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        ftp.rmd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users/"+meli_code_get)
                        m.clear()
                        m.pencolor("brown")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.حذف کاربر با موفقيت انجام شد',align="center",font=("B Nazanin",13,("bold")))
                    elif("ليست"in what):
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users/")
                        users=ftp.nlst()
                        users=users[2:]
                        t.clear()
                        m.clear()
                        button1.ht()
                        button2.ht()
                        button3.ht()
                        button4.ht()
                        button5.ht()
                        button6.ht()
                        hi=(len(users)*180)
                        win_width, win_height, bg_color = 350, hi, 'gray'
                        t.setup(350,410)
                        t.screensize(win_width, win_height, bg_color)
                        t.pu()
                        t.goto(0,90)
                        t.pd()
                        t.pencolor("black")
                        t.write("ليست کردن کاربر ها ممکن است،\n.ساعت ها زمان ببرد",align="center",font=("B Nazanin",13,("bold")))
                        t.pu()
                        t.goto(0,20)
                        t.pd()
                        t.pencolor("purple")
                        t.write("مي توانيد با استفاده از کليد،\n.جستجو کنيد 's'",align="center",font=("B Titr",12,("bold")))
                        t.pu()
                        t.goto(0,-30)
                        t.pd()
                        t.pencolor("darkblue")
                        t.write("* * * *",align="center",font=("B Titr",12,("bold")))
                        for i in range (0,len(users)):
                            t.pu()
                            t.goto(0,(i+1)*-80)
                            lolo=(i+1)*-80
                            t.pd()
                            t.pencolor("darkred")
                            t.write((str(i+1)+"- "+users[i]),align="center",font=("Perpetua Titling MT",13,("bold")))
                            ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                            ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users/"+users[i])
                            hhjo=ftp.nlst()
                            ftp.cwd(hhjo[2])
                            hhhjo=ftp.nlst()
                            for i in range(0,len(hhhjo)-2):
                                if(hhhjo[i+2]!="books"):
                                    try:
                                        int(hhhjo[i+2])
                                    except:
                                        jojo=hhhjo[i+2]
                            t.pu()
                            t.goto(0,lolo-20)
                            t.pd()
                            t.pencolor("black")
                            t.write(jojo,align="center",font=("Rockwell",12,("bold")))
                        def key3():
                            subjectsearch=t.textinput("ليست",": کد ملي")
                            if(subjectsearch in users):
                                root = tkinter.Tk()
                                root.withdraw()
                                messagebox.showinfo("نتايج",".بله، اين کاربر در کتابخانه وجود دارد")
                            else:
                                root = tkinter.Tk()
                                root.withdraw()
                                messagebox.showinfo("نتايج",".خير، اين کاربر در کتابخانه وجود ندارد")
                        scr.onkey(key3,"s")
                        scr.listen()
                except:
                    m.pencolor("purple")
                    m.clear()
                    m.pu()
                    m.goto(0,20)
                    m.pd()
                    m.write('.مشکلي در بخش کاربر ها رخ داده است',align="center",font=("B Nazanin",13,("bold")))
            def buton4(x,y):
                try:
                    m.clear()
                    m.pencolor("darkblue")
                    m.pu()
                    m.goto(0,20)
                    m.pd()
                    m.write('.لطفا نوع درخواست را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                    what=t.textinput("کتاب ها",": ( افزودن / حذف / ليست )")
                    if("افزودن"in what):
                        m.clear()
                        m.pencolor("darkblue")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.لطفا شابک کتاب را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                        shabak_code_get=t.textinput("افزودن",": شابک کتاب")
                        m.clear()
                        m.pencolor("darkblue")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.لطفا نام کتاب را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                        name_book=t.textinput("افزودن",":*نام کتاب، *الزاما انگليسي وارد کنيد")
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books")
                        ftp.mkd(shabak_code_get)
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books/"+shabak_code_get)
                        ftp.mkd(name_book)
                        ftp.mkd("exists")
                        m.clear()
                        m.pencolor("brown")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.ثبت کتاب با موفقيت انجام شد',align="center",font=("B Nazanin",13,("bold")))
                    elif("حذف"in what):
                        m.clear()
                        m.pencolor("darkblue")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.لطفا شابک کتاب را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                        shabak_code_get=t.textinput("حذف",": شابک کتاب")
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books/"+shabak_code_get)
                        hhko=ftp.nlst()
                        for i in range(0,len(hhko)-2):
                            ftp.rmd(hhko[i+2])
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books/")
                        ftp.rmd(shabak_code_get)
                        m.clear()
                        m.pencolor("brown")
                        m.pu()
                        m.goto(0,20)
                        m.pd()
                        m.write('.حذف کتاب با موفقيت انجام شد',align="center",font=("B Nazanin",13,("bold")))
                    elif("ليست"in what):
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books/")
                        books=ftp.nlst()
                        books=books[2:]
                        t.clear()
                        m.clear()
                        button1.ht()
                        button2.ht()
                        button3.ht()
                        button4.ht()
                        button5.ht()
                        button6.ht()
                        hi=((len(books)*180))
                        win_width, win_height, bg_color = 350,hi, 'gray'
                        t.setup(350,410)
                        t.screensize(win_width, win_height, bg_color)
                        t.pu()
                        t.goto(0,90)
                        t.pd()
                        t.pencolor("black")
                        t.write("،ليست کردن کتاب ها ممکن است\n.ساعت ها زمان ببرد",align="center",font=("B Nazanin",13,("bold")))
                        t.pu()
                        t.goto(0,20)
                        t.pd()
                        t.pencolor("purple")
                        t.write("،مي توانيد با استفاده از کليد\n.جستجو کنيد 's'",align="center",font=("B Titr",12,("bold")))
                        t.pu()
                        t.goto(0,-30)
                        t.pd()
                        t.pencolor("darkblue")
                        t.write("* * * *",align="center",font=("B Titr",12,("bold")))
                        for i in range (0,len(books)):  
                            t.pu()
                            t.goto(0,(i+1)*-80)
                            t.pd()
                            lolo=(i+1)*-80
                            t.pencolor("darkred")
                            t.write((str(i+1)+"- "+books[i]),align="center",font=("Perpetua Titling MT",13,("bold")))
                            ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                            ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/books/"+books[i])
                            hhjo=ftp.nlst()
                            t.pu()
                            t.goto(0,lolo-20)
                            t.pd()
                            t.pencolor("black")
                            for i in range(2,4):
                                try:
                                    jojoo=hhjo[i]
                                    if(jojoo!="exists"):
                                           karaj=jojoo
                                except:
                                    pass
                            t.write(karaj,align="center",font=("Rockwell",12,("bold")))
                        def key3():
                            subjectsearch=t.textinput("ليست",": شابک کتاب")
                            if(subjectsearch in books):
                                root = tkinter.Tk()
                                root.withdraw()
                                messagebox.showinfo("نتايج",".بله، اين شابک در کتابخانه وارد شده است")
                            else:
                                root = tkinter.Tk()
                                root.withdraw()
                                messagebox.showinfo("نتايج",".خير، اين شابک در کتابخانه وارد نشده است")
                        scr.onkey(key3,"s")
                        scr.listen()
                except:
                    m.pencolor("purple")
                    m.clear()
                    m.pu()
                    m.goto(0,20)
                    m.pd()
                    m.write('.مشکلي در بخش کتاب ها رخ داده است',align="center",font=("B Nazanin",13,("bold")))
            def buton5(x,y):
                m.clear()
                m.pu()
                m.goto(0,85)
                m.pd()
                m.pencolor("brown")
                m.write("،اطلاعات",align="center",font=("B Nazanin",15,("bold")))
                m.pu()
                m.goto(0,28)
                m.pd()
                m.pencolor("black")
                m.write('مدير کتابخانه "کاتب" 1.3\n© 2018 تمامي حقوق محفوظ است. | کدفي',align="center",font=("B Nazanin",15))
                m.pu()
                m.goto(0,-70)
                m.pd()
                m.pencolor("darkblue")
                m.write("مدير اجرايي : اميرحسين صفرزاده\nمدير گروه : آريا ايزانلو\nرابط کاربري - طراحي شده توسط کدفي",align="center",font=("B Nazanin",15))
            def buton6(x,y):
                try:
                    m.clear()
                    m.pencolor("darkblue")
                    m.pu()
                    m.goto(0,20)
                    m.pd()
                    m.write('.لطفا نوع اعلان را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                    what=t.textinput("اعلانات",": ( ديرکرد / ارسال )")
                    if("ديرکرد" in what):
                        ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                        ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users/")
                        usersd=ftp.nlst()
                        for i in range(0,len(usersd)-2):
                            ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                            ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users/")
                            ftp.cwd(usersd[i+2])
                            xx=ftp.nlst()
                            ftp.cwd(xx[2])
                            ftp.cwd("books")
                            booksu=ftp.nlst()
                            now=datetime.now()
                            users_dir=[]
                            try:
                                ftp.cwd(booksu[2])
                                tibo=ftp.nlst()
                                date1=tibo[2]
                                d0 = date(int(jdatetime.datetime.now().strftime("13"+str("%y"))), int(jdatetime.datetime.now().strftime("%m")), int(jdatetime.datetime.now().strftime("%d")))
                                date2=str(date1)
                                d1 = date(int(date2[0:4]),int(date2[5:7]),int(date2[8:]))
                                delta = d0 - d1
                                if(int(delta.days)>7):
                                    users_dir.append(usersd[i+2])
                                try:
                                    ftp.cwd(booksu[3])
                                    tibt=ftp.nlst()
                                    date1=tibt[2]
                                    d0 = date(int(jdatetime.datetime.now().strftime("13"+str("%y"))), int(jdatetime.datetime.now().strftime("%m")), int(jdatetime.datetime.now().strftime("%d")))
                                    date2=str(date1)
                                    d1 = date(int(date2[0:4]),int(date2[5:7]),int(date2[8:]))
                                    delta = d0 - d1
                                    if(int(delta.days)>7):
                                        users_dir.append(usersd[i+2])
                                except:
                                    pass
                            except:
                                pass
                        if(len(users_dir)>=1):
                            print(users_dir)
                            t.clear()
                            m.clear()
                            button1.ht()
                            button2.ht()
                            button3.ht()
                            button4.ht()
                            button5.ht()
                            button6.ht()
                            hi=((len(books)*180))
                            win_width, win_height, bg_color = 350,hi, 'gray'
                            t.setup(350,410)
                            t.screensize(win_width, win_height, bg_color)
                            t.pu()
                            t.goto(0,90)
                            t.pd()
                            t.pencolor("black")
                            t.write("،ليست کردن کاربر ها ممکن است\n.ساعت ها زمان ببرد",align="center",font=("B Nazanin",13,("bold")))
                            t.pu()
                            t.goto(0,20)
                            t.pd()
                            t.pencolor("purple")
                            t.write("،مي توانيد با استفاده از کليد\n.جستجو کنيد 's'",align="center",font=("B Titr",12,("bold")))
                            t.pu()
                            t.goto(0,-30)
                            t.pd()
                            t.pencolor("darkblue")
                            t.write("* * * *",align="center",font=("B Titr",12,("bold")))
                            for i in range (0,len(users_dir)):
                                t.pu()
                                t.goto(0,(i+1)*-80)
                                t.pd()
                                t.pencolor("darkred")
                                t.write((str(i+1)+"- "+users_dir[i]),align="center",font=("Perpetua Titling MT",13,("bold")))
                            def key3():
                                subjectsearch=t.textinput("ليست",": کد ملي")
                                if(subjectsearch in users_dir):
                                    root = tkinter.Tk()
                                    root.withdraw()
                                    messagebox.showinfo("نتايج",".بله، اين کاربر در ليست ديرکرد ها وجود دارد")
                                else:
                                    root = tkinter.Tk()
                                    root.withdraw()
                                    messagebox.showinfo("نتايج",".خير، اين کاربر در کتابخانه وجود ندارد")
                            scr.onkey(key3,"s")
                            scr.listen()
                        else:
                            m.pencolor("purple")
                            m.clear()
                            m.pu()
                            m.goto(0,20)
                            m.pd()
                            m.write('.در حال حاضر فردي در ليست ديرکرد شناسايي نشد',align="center",font=("B Nazanin",13,("bold")))
                    elif("ارسال" in what):
                        try:
                            m.pencolor("darkblue")
                            m.clear()
                            m.pu()
                            m.goto(0,20)
                            m.pd()
                            m.write('.لطفا کد ملي مخاطب را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                            mellic=t.textinput("ارسال",": کد ملي")
                            m.pencolor("darkblue")
                            m.clear()
                            m.pu()
                            m.goto(0,20)
                            m.pd()
                            m.write('.لطفا پيام خود را وارد کنيد',align="center",font=("B Nazanin",13,("bold")))
                            mofu=t.textinput("ارسال",": پيام")
                            ftp=ftplib.FTP("ftpupload.net","cldff_22998458","arizamir")
                            ftp.cwd("htdocs/"+admin_id+'/'+admin_pass+"/LB/users/"+mellic)
                            passofu=ftp.nlst()
                            ftp.cwd(passofu[2])
                            numberofu=ftp.nlst()
                            requests.get("http://37.130.202.188/class/sms/webservice/send_url.php?from=+98100009&to="+numberofu[2]+"&msg="+mofu+"&uname=safarzadeh2580&pass=codoffeearizamir")
                            m.pencolor("brown")
                            m.clear()
                            m.pu()
                            m.goto(0,20)
                            m.pd()
                            m.write('.ارسال پيام موفقيت آميز بود',align="center",font=("B Nazanin",13,("bold")))
                        except:
                            m.pencolor("purple")
                            m.clear()
                            m.pu()
                            m.goto(0,20)
                            m.pd()  
                            m.write('.مشکلي در بخش ارسال پيام پيش آمده است',align="center",font=("B Nazanin",13,("bold")))
                except:
                    m.pencolor("purple")
                    m.clear()
                    m.pu()
                    m.goto(0,20)
                    m.pd()
                    m.write('.مشکلي در بخش اعلانات پيش آمده است',align="center",font=("B Nazanin",13,("bold"))) 
            def key1():
                print("key1")
            def key2():
                print("key2")
            m.clear()
            m.pu()
            m.goto(0,0)
            m.pd()
            m.pencolor("darkorange")
            m.write('مدير کتابخانه "کاتب" 1.3 | حساب مدير',align="center",font=("B Titr",15))
            button1.onclick(buton1)
            button2.onclick(buton2)
            button3.onclick(buton3)
            button4.onclick(buton4)
            button5.onclick(buton5)
            button6.onclick(buton6)
            scr.onkey(key1,"space")
            scr.onkey(key2,"d")
            scr.listen()
            def date_time():
                dt=t.Turtle()
                dt.speed(0)
                jdatetime.set_locale('fa_IR')
                while True:
                    dt.ht()
                    now=datetime.now()
                    now_date=jdatetime.datetime.now().strftime("%Y/%m/%d")
                    now_time=jdatetime.datetime.now().strftime("%H:%M")
                    dt.clear()
                    dt.pu()
                    dt.goto(270,218)
                    dt.pd()
                    dt.pencolor(p_color)
                    dt.write(now_time,align="center",font=("B Titr",15))
                    dt.pu()
                    dt.goto(-250,218)
                    dt.pd()
                    dt.write(now_date,align="center",font=("B Titr",15))
                    time.sleep(59.9)
            thread1=Thread(target=date_time,args=[])
            thread1.start()
            t.mainloop()
        except:
            pass
    except:
        pass
except:
    scr.reset()
    button1.ht()
    button2.ht()
    button3.ht()
    button4.ht()
    button5.ht()
    button6.ht()
    m.ht()
    t.ht()
    dcw.ht()
    t.bgcolor("gray")
    t.clear()
    t.pencolor("brown")
    t.pu()
    t.goto(0,0)
    t.pd()
    t.write("Error",align="center",font=("Arial",25,("bold")))
    time.sleep(2)
    t.clear()
    t.pencolor("pink")
    t.pu()
    t.goto(0,0)
    t.pd()
    t.write("خطا",align="center",font=("B Titr",25,("bold")))
    playsound.playsound("14.mp3")
#End, Total codes: 1020 line:----------------------------------------------------Codoffee Library M V1.5--------------------------------------------------------------
#Thanks from:
    #Mr.Izanlou-CodoffeeManager
    #Mr.Safarzadeh-CodoffeeManager
    #Proudly-PoweredBy-PythonTkinter-C++/C-PL
